//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public string Id { get; set; }
        public string ComputerName { get; set; }
        public bool IsConfirmChanged { get; set; }
        public Nullable<bool> IsOldVersionOS { get; set; }
        public Nullable<bool> IsOldVersionAntivirus { get; set; }
    }
}
