//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UndefinedSoftware
    {
        public int Id { get; set; }
        public Nullable<int> InformationId { get; set; }
        public string ComputerName { get; set; }
        public string UndefinedSoftware1 { get; set; }
        public string Name { get; set; }
        public string CreateDate { get; set; }
        public string Size { get; set; }
        public string Location { get; set; }
    
        public virtual Information Information { get; set; }
    }
}
